let
    Origen = Excel.Workbook(File.Contents("C:\Users\sleyton\BNV\Administración y Finanzas - Documentos\Inteligencia de negocios\Formatos para reportes PBI\CIVITAS.xlsx"), null, true),
    #"KPIS Atempora_Sheet" = Origen{[Item="KPIS Atempora",Kind="Sheet"]}[Data],
    #"Encabezados promovidos" = Table.PromoteHeaders(#"KPIS Atempora_Sheet", [PromoteAllScalars=true]),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Proyecto", type text}, {"Ocupacion Ventas OF", type number}, {"Ocupacion Renta OF", type number}, {"M2 vendidos OF", type number}, {"m2 arrendados OF", type number}, {"Disponible OF", type number}, {"Reserva Arriendo OF", type number}, {"Reserva Compra OF", Int64.Type}, {"uf/m2 venta OF", type number}, {"uf/m2 arriendo OF", type number}, {"Unidades Vendidas OF", Int64.Type}, {"Unidades Arrendadas OF", Int64.Type}, {"Unidades reservadas  ARR OF", Int64.Type}, {"Unidades reservadas  Vent OF", Int64.Type}, {"Unidades Disponibles OF", Int64.Type}, {"Ocupacion Ventas LC", type number}, {"Ocupacion Renta LC", type number}, {"M2 vendidos LC", type number}, {"m2 arrendados LC", type number}, {"uf/m2 venta LC", type number}, {"uf/m2 arriendo LC", type number}, {"Unidades Vendidas LC", Int64.Type}, {"Unidades Arrendadas LC", Int64.Type}, {"Unidades Disponibles LC", Int64.Type}, {"Fecha ", type date}, {"Mes", Int64.Type}, {"Año", Int64.Type}, {"Fecha ID", Int64.Type}, {"Of total", Int64.Type}, {"LC Total", Int64.Type}, {"Gasto Comun", type number}, {"M2 occ totales", type number}, {"Ocupacion total", type number}})
in
    #"Tipo cambiado"