let
    Origen = Excel.Workbook(File.Contents("C:\Users\sleyton\BNV\Administración y Finanzas - Documentos\Inteligencia de negocios\Formatos para reportes PBI\Renta Residencial .xlsx"), null, true),
    #"Real+PPTO+LY_Sheet" = Origen{[Item="Real+PPTO+LY",Kind="Sheet"]}[Data],
    #"Encabezados promovidos" = Table.PromoteHeaders(#"Real+PPTO+LY_Sheet", [PromoteAllScalars=true]),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Periodo", type date}, {"Activo", type text}, {"Ingresos totales UF p", type number}, {"Costos operacionales UF p", type number}, {"EBITDA UF p", type number}, {"Flujo UF p", type number}, {"EBITDA UF/CUOTA BANCO p", type number}, {"Ocupación departamentos 2022 (%) p", type number}, {"EBITDA UF/VENTAS p", type number}, {"Ingresos totales UF YTD p", type number}, {"Costos operacionales UF YTD p", type number}, {"EBITDA UF YTD p", type number}, {"Flujo UF YTD p", type number}, {"Año p", Int64.Type}, {"Mes p", Int64.Type}, {"Ingresos totales UF R", type number}, {"Costos operacionales UF R", type number}, {"EBITDA UF R", type number}, {"Flujo UF R", type number}, {"EBITDA UF/CUOTA BANCO R", type number}, {"Ocupación departamentos 2022 (%) R", type number}, {"Ingresos totales UF YTD R", type number}, {"Costos operacionales UF YTD R", type number}, {"EBITDA UF YTD R", type number}, {"Flujo UF YTD R", type number}, {"Año", Int64.Type}, {"Mes", Int64.Type}, {"LY fecha", type date}, {"Check", type number}, {"Ingresos totales UF R LY", type number}, {"Costos operacionales UF LY", type number}, {"EBITDA UF R LY", type number}, {"Flujo UF R LY", type number}, {"EBITDA UF/CUOTA BANCO R LY", type number}, {"Ocupación departamentos 2022 (%) R7 LY", type number}, {"EBITDA UF/VENTAS R LY", type number}, {"Gastos Comunes (UF/M2) R", type number}, {"Gastos Comunes (UF/M2) P", type number}, {"UF/M2_DEPARTAMENTOS R ", type number}, {"UF/M2_YTD R", type number}, {"UF/ESTACIONAMIENTO R", type number}, {"UF/ESTACIONAMIENTO_YTD R", type number}, {"UF/M2 (DEPTO+ESTAC.) R", type number}, {"UF/M2 (DEPTO+ESTAC.)_YTD R", type number}, {"Fecha ID", Int64.Type}, {"UF/M2_DEPARTAMENTOS p", type number}, {"UF/M2_YTD p", type number}, {"UF/ESTACIONAMIENTO p", type number}, {"UF/ESTACIONAMIENTO_YTD p", type number}, {"UF/M2 (DEPTO+ESTAC.) p", type number}, {"UF/M2 (DEPTO+ESTAC.)_YTD p", type number}, {"Tarifa LY", type number}, {"Gasto comun LY", type number}})
in
    #"Tipo cambiado"